### ISSUE TITLE
Check CLDF forms column

### ISSUE THREAD

**Issue by chrzyki** [lexibank/satterthwaitetb#4]
Seems as if tones aren't converted properly?

**Comment by johenglisch** [comment]
Hm, what should the tones be converted to, actually?  Is there a ‘standard form’ that pylexibank can understand?

**Comment by LinguList** [comment]
What does this mean? Tones would be important only for the Segments, right? But this dataset has no segments, only forms...

**Comment by johenglisch** [comment]
Oh, yeah…  I think we just got worried because of the massive output of `check_phonotactics`.  I guess we can ignore that if there isn't actually any segmentation/phonotactics info being processed. (<_<)"

**Comment by LinguList** [comment]
Yep. The phonotactics don't need to be checked if the dataset is not 
qualified as "lexicore" ;)

**Comment by johenglisch** [comment]
Okay, thanks for reminding us – it's easy to get stuck in a loop sometimes when releasing dozens of datasets one after another. \*ggg*

**Comment by chrzyki** [comment]
Please check the form column. Tones seem to be just plain numbers there, I was referring to that.

**Comment by chrzyki** [comment]
Aka we wouldn't want those numbers simply as plain numbers in the forms column, correct?

**Comment by johenglisch** [comment]
Okay, then what would we preferably include instead?  IPA tone marks `꜒`?  Superscript numbers `¹`?

EDIT: typo, phrasing

**Comment by LinguList** [comment]
Why not? I mean: The author made this as a form sheet, and if you search for colexifications, you'll find the forms as `ka 55`, which is awkward, but something that the source gives us. So I'd say: it does not matter. A profile would be needed to make this regular, but we decided that this dataset is too unsteady to use a profile, so we ignore it and take the form at face value (as it is also in the original PDF of the publication).

**Comment by LinguList** [comment]
BTW: tone is often represented as `ka⁵⁵`, and typically, many authors write `ka55`, since they do not want to write superscript numbers, so there's no problem with this.

**Comment by chrzyki** [comment]
Thanks for clarifying.
